/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminEntrarRouteImport } from './routes/admin-entrar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEstabelecimentoRouteImport } from './routes/_authenticated/estabelecimento'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated/entregador'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEstabelecimentoIndexRouteImport } from './routes/_authenticated/estabelecimento.index'
import { Route as AuthenticatedEntregadorIndexRouteImport } from './routes/_authenticated/entregador.index'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'
import { Route as AuthenticatedEstabelecimentoSaquesRouteImport } from './routes/_authenticated/estabelecimento.saques'
import { Route as AuthenticatedEstabelecimentoRelatoriosRouteImport } from './routes/_authenticated/estabelecimento.relatorios'
import { Route as AuthenticatedEstabelecimentoProdutosRouteImport } from './routes/_authenticated/estabelecimento.produtos'
import { Route as AuthenticatedEstabelecimentoPedidosRouteImport } from './routes/_authenticated/estabelecimento.pedidos'
import { Route as AuthenticatedEstabelecimentoHorariosRouteImport } from './routes/_authenticated/estabelecimento.horarios'
import { Route as AuthenticatedEstabelecimentoFinanceiroRouteImport } from './routes/_authenticated/estabelecimento.financeiro'
import { Route as AuthenticatedEstabelecimentoExtratoRouteImport } from './routes/_authenticated/estabelecimento.extrato'
import { Route as AuthenticatedEstabelecimentoEstoqueRouteImport } from './routes/_authenticated/estabelecimento.estoque'
import { Route as AuthenticatedEstabelecimentoEquipeRouteImport } from './routes/_authenticated/estabelecimento.equipe'
import { Route as AuthenticatedEstabelecimentoEntregaRouteImport } from './routes/_authenticated/estabelecimento.entrega'
import { Route as AuthenticatedEstabelecimentoCuponsRouteImport } from './routes/_authenticated/estabelecimento.cupons'
import { Route as AuthenticatedEstabelecimentoConfiguracoesRouteImport } from './routes/_authenticated/estabelecimento.configuracoes'
import { Route as AuthenticatedEstabelecimentoComplementosRouteImport } from './routes/_authenticated/estabelecimento.complementos'
import { Route as AuthenticatedEstabelecimentoCategoriasRouteImport } from './routes/_authenticated/estabelecimento.categorias'
import { Route as AuthenticatedEstabelecimentoCarteiraRouteImport } from './routes/_authenticated/estabelecimento.carteira'
import { Route as AuthenticatedEstabelecimentoBannersRouteImport } from './routes/_authenticated/estabelecimento.banners'
import { Route as AuthenticatedEstabelecimentoAvaliacoesRouteImport } from './routes/_authenticated/estabelecimento.avaliacoes'
import { Route as AuthenticatedEntregadorVeiculoRouteImport } from './routes/_authenticated/entregador.veiculo'
import { Route as AuthenticatedEntregadorSuporteRouteImport } from './routes/_authenticated/entregador.suporte'
import { Route as AuthenticatedEntregadorSaquesRouteImport } from './routes/_authenticated/entregador.saques'
import { Route as AuthenticatedEntregadorPerfilRouteImport } from './routes/_authenticated/entregador.perfil'
import { Route as AuthenticatedEntregadorNotificacoesRouteImport } from './routes/_authenticated/entregador.notificacoes'
import { Route as AuthenticatedEntregadorMetasRouteImport } from './routes/_authenticated/entregador.metas'
import { Route as AuthenticatedEntregadorHistoricoRouteImport } from './routes/_authenticated/entregador.historico'
import { Route as AuthenticatedEntregadorGanhosRouteImport } from './routes/_authenticated/entregador.ganhos'
import { Route as AuthenticatedEntregadorDocumentosRouteImport } from './routes/_authenticated/entregador.documentos'
import { Route as AuthenticatedEntregadorCorridasRouteImport } from './routes/_authenticated/entregador.corridas'
import { Route as AuthenticatedEntregadorConfiguracoesRouteImport } from './routes/_authenticated/entregador.configuracoes'
import { Route as AuthenticatedEntregadorChatRouteImport } from './routes/_authenticated/entregador.chat'
import { Route as AuthenticatedEntregadorCarteiraRouteImport } from './routes/_authenticated/entregador.carteira'
import { Route as AuthenticatedEntregadorAvaliacoesRouteImport } from './routes/_authenticated/entregador.avaliacoes'
import { Route as AuthenticatedClientePedidosRouteImport } from './routes/_authenticated/cliente.pedidos'
import { Route as AuthenticatedClienteNovidadesRouteImport } from './routes/_authenticated/cliente.novidades'
import { Route as AuthenticatedClienteFavoritosRouteImport } from './routes/_authenticated/cliente.favoritos'
import { Route as AuthenticatedClienteCheckoutRouteImport } from './routes/_authenticated/cliente.checkout'
import { Route as AuthenticatedClienteCarrinhoRouteImport } from './routes/_authenticated/cliente.carrinho'
import { Route as AuthenticatedClienteBuscarRouteImport } from './routes/_authenticated/cliente.buscar'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminSaquesRouteImport } from './routes/_authenticated/admin.saques'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminMapaRouteImport } from './routes/_authenticated/admin.mapa'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminIaRouteImport } from './routes/_authenticated/admin.ia'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEstabelecimentosRouteImport } from './routes/_authenticated/admin.estabelecimentos'
import { Route as AuthenticatedAdminEntregadoresRouteImport } from './routes/_authenticated/admin.entregadores'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCampanhasRouteImport } from './routes/_authenticated/admin.campanhas'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAvaliacoesRouteImport } from './routes/_authenticated/admin.avaliacoes'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'
import { Route as AuthenticatedClientePerfilIndexRouteImport } from './routes/_authenticated/cliente.perfil.index'
import { Route as AuthenticatedEntregadorPerfilPagamentoRouteImport } from './routes/_authenticated/entregador.perfil.pagamento'
import { Route as AuthenticatedEntregadorPerfilDadosRouteImport } from './routes/_authenticated/entregador.perfil.dados'
import { Route as AuthenticatedClientePerfilTermosRouteImport } from './routes/_authenticated/cliente.perfil.termos'
import { Route as AuthenticatedClientePerfilRecompensasRouteImport } from './routes/_authenticated/cliente.perfil.recompensas'
import { Route as AuthenticatedClientePerfilNotificacoesRouteImport } from './routes/_authenticated/cliente.perfil.notificacoes'
import { Route as AuthenticatedClientePerfilEnderecosRouteImport } from './routes/_authenticated/cliente.perfil.enderecos'
import { Route as AuthenticatedClientePerfilDispositivoRouteImport } from './routes/_authenticated/cliente.perfil.dispositivo'
import { Route as AuthenticatedClientePerfilContaRouteImport } from './routes/_authenticated/cliente.perfil.conta'
import { Route as AuthenticatedClientePerfilClubeRouteImport } from './routes/_authenticated/cliente.perfil.clube'
import { Route as AuthenticatedClientePerfilAjudaRouteImport } from './routes/_authenticated/cliente.perfil.ajuda'
import { Route as AuthenticatedClientePedidoIdRouteImport } from './routes/_authenticated/cliente.pedido.$id'
import { Route as AuthenticatedClienteEstabelecimentoIdRouteImport } from './routes/_authenticated/cliente.estabelecimento.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin-entrar',
  path: '/admin-entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstabelecimentoRoute =
  AuthenticatedEstabelecimentoRouteImport.update({
    id: '/estabelecimento',
    path: '/estabelecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstabelecimentoIndexRoute =
  AuthenticatedEstabelecimentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEntregadorIndexRoute =
  AuthenticatedEntregadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstabelecimentoSaquesRoute =
  AuthenticatedEstabelecimentoSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoRelatoriosRoute =
  AuthenticatedEstabelecimentoRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoProdutosRoute =
  AuthenticatedEstabelecimentoProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoPedidosRoute =
  AuthenticatedEstabelecimentoPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoHorariosRoute =
  AuthenticatedEstabelecimentoHorariosRouteImport.update({
    id: '/horarios',
    path: '/horarios',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoFinanceiroRoute =
  AuthenticatedEstabelecimentoFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoExtratoRoute =
  AuthenticatedEstabelecimentoExtratoRouteImport.update({
    id: '/extrato',
    path: '/extrato',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoEstoqueRoute =
  AuthenticatedEstabelecimentoEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoEquipeRoute =
  AuthenticatedEstabelecimentoEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoEntregaRoute =
  AuthenticatedEstabelecimentoEntregaRouteImport.update({
    id: '/entrega',
    path: '/entrega',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoCuponsRoute =
  AuthenticatedEstabelecimentoCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoConfiguracoesRoute =
  AuthenticatedEstabelecimentoConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoComplementosRoute =
  AuthenticatedEstabelecimentoComplementosRouteImport.update({
    id: '/complementos',
    path: '/complementos',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoCategoriasRoute =
  AuthenticatedEstabelecimentoCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoCarteiraRoute =
  AuthenticatedEstabelecimentoCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoBannersRoute =
  AuthenticatedEstabelecimentoBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEstabelecimentoAvaliacoesRoute =
  AuthenticatedEstabelecimentoAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedEstabelecimentoRoute,
  } as any)
const AuthenticatedEntregadorVeiculoRoute =
  AuthenticatedEntregadorVeiculoRouteImport.update({
    id: '/veiculo',
    path: '/veiculo',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorSuporteRoute =
  AuthenticatedEntregadorSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorSaquesRoute =
  AuthenticatedEntregadorSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorPerfilRoute =
  AuthenticatedEntregadorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorNotificacoesRoute =
  AuthenticatedEntregadorNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorMetasRoute =
  AuthenticatedEntregadorMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorHistoricoRoute =
  AuthenticatedEntregadorHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorGanhosRoute =
  AuthenticatedEntregadorGanhosRouteImport.update({
    id: '/ganhos',
    path: '/ganhos',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorDocumentosRoute =
  AuthenticatedEntregadorDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorCorridasRoute =
  AuthenticatedEntregadorCorridasRouteImport.update({
    id: '/corridas',
    path: '/corridas',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorConfiguracoesRoute =
  AuthenticatedEntregadorConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorChatRoute =
  AuthenticatedEntregadorChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorCarteiraRoute =
  AuthenticatedEntregadorCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedEntregadorAvaliacoesRoute =
  AuthenticatedEntregadorAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedClientePedidosRoute =
  AuthenticatedClientePedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteNovidadesRoute =
  AuthenticatedClienteNovidadesRouteImport.update({
    id: '/novidades',
    path: '/novidades',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteFavoritosRoute =
  AuthenticatedClienteFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteCheckoutRoute =
  AuthenticatedClienteCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteCarrinhoRoute =
  AuthenticatedClienteCarrinhoRouteImport.update({
    id: '/carrinho',
    path: '/carrinho',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteBuscarRoute =
  AuthenticatedClienteBuscarRouteImport.update({
    id: '/buscar',
    path: '/buscar',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaquesRoute =
  AuthenticatedAdminSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMapaRoute = AuthenticatedAdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIaRoute = AuthenticatedAdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstabelecimentosRoute =
  AuthenticatedAdminEstabelecimentosRouteImport.update({
    id: '/estabelecimentos',
    path: '/estabelecimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntregadoresRoute =
  AuthenticatedAdminEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampanhasRoute =
  AuthenticatedAdminCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvaliacoesRoute =
  AuthenticatedAdminAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientePerfilIndexRoute =
  AuthenticatedClientePerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedEntregadorPerfilPagamentoRoute =
  AuthenticatedEntregadorPerfilPagamentoRouteImport.update({
    id: '/pagamento',
    path: '/pagamento',
    getParentRoute: () => AuthenticatedEntregadorPerfilRoute,
  } as any)
const AuthenticatedEntregadorPerfilDadosRoute =
  AuthenticatedEntregadorPerfilDadosRouteImport.update({
    id: '/dados',
    path: '/dados',
    getParentRoute: () => AuthenticatedEntregadorPerfilRoute,
  } as any)
const AuthenticatedClientePerfilTermosRoute =
  AuthenticatedClientePerfilTermosRouteImport.update({
    id: '/perfil/termos',
    path: '/perfil/termos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilRecompensasRoute =
  AuthenticatedClientePerfilRecompensasRouteImport.update({
    id: '/perfil/recompensas',
    path: '/perfil/recompensas',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilNotificacoesRoute =
  AuthenticatedClientePerfilNotificacoesRouteImport.update({
    id: '/perfil/notificacoes',
    path: '/perfil/notificacoes',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilEnderecosRoute =
  AuthenticatedClientePerfilEnderecosRouteImport.update({
    id: '/perfil/enderecos',
    path: '/perfil/enderecos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilDispositivoRoute =
  AuthenticatedClientePerfilDispositivoRouteImport.update({
    id: '/perfil/dispositivo',
    path: '/perfil/dispositivo',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilContaRoute =
  AuthenticatedClientePerfilContaRouteImport.update({
    id: '/perfil/conta',
    path: '/perfil/conta',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilClubeRoute =
  AuthenticatedClientePerfilClubeRouteImport.update({
    id: '/perfil/clube',
    path: '/perfil/clube',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilAjudaRoute =
  AuthenticatedClientePerfilAjudaRouteImport.update({
    id: '/perfil/ajuda',
    path: '/perfil/ajuda',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePedidoIdRoute =
  AuthenticatedClientePedidoIdRouteImport.update({
    id: '/pedido/$id',
    path: '/pedido/$id',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteEstabelecimentoIdRoute =
  AuthenticatedClienteEstabelecimentoIdRouteImport.update({
    id: '/estabelecimento/$id',
    path: '/estabelecimento/$id',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-entrar': typeof AdminEntrarRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/entregador': typeof AuthenticatedEntregadorRouteWithChildren
  '/estabelecimento': typeof AuthenticatedEstabelecimentoRouteWithChildren
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/estabelecimentos': typeof AuthenticatedAdminEstabelecimentosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/buscar': typeof AuthenticatedClienteBuscarRoute
  '/cliente/carrinho': typeof AuthenticatedClienteCarrinhoRoute
  '/cliente/checkout': typeof AuthenticatedClienteCheckoutRoute
  '/cliente/favoritos': typeof AuthenticatedClienteFavoritosRoute
  '/cliente/novidades': typeof AuthenticatedClienteNovidadesRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/entregador/avaliacoes': typeof AuthenticatedEntregadorAvaliacoesRoute
  '/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/entregador/chat': typeof AuthenticatedEntregadorChatRoute
  '/entregador/configuracoes': typeof AuthenticatedEntregadorConfiguracoesRoute
  '/entregador/corridas': typeof AuthenticatedEntregadorCorridasRoute
  '/entregador/documentos': typeof AuthenticatedEntregadorDocumentosRoute
  '/entregador/ganhos': typeof AuthenticatedEntregadorGanhosRoute
  '/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/entregador/metas': typeof AuthenticatedEntregadorMetasRoute
  '/entregador/notificacoes': typeof AuthenticatedEntregadorNotificacoesRoute
  '/entregador/perfil': typeof AuthenticatedEntregadorPerfilRouteWithChildren
  '/entregador/saques': typeof AuthenticatedEntregadorSaquesRoute
  '/entregador/suporte': typeof AuthenticatedEntregadorSuporteRoute
  '/entregador/veiculo': typeof AuthenticatedEntregadorVeiculoRoute
  '/estabelecimento/avaliacoes': typeof AuthenticatedEstabelecimentoAvaliacoesRoute
  '/estabelecimento/banners': typeof AuthenticatedEstabelecimentoBannersRoute
  '/estabelecimento/carteira': typeof AuthenticatedEstabelecimentoCarteiraRoute
  '/estabelecimento/categorias': typeof AuthenticatedEstabelecimentoCategoriasRoute
  '/estabelecimento/complementos': typeof AuthenticatedEstabelecimentoComplementosRoute
  '/estabelecimento/configuracoes': typeof AuthenticatedEstabelecimentoConfiguracoesRoute
  '/estabelecimento/cupons': typeof AuthenticatedEstabelecimentoCuponsRoute
  '/estabelecimento/entrega': typeof AuthenticatedEstabelecimentoEntregaRoute
  '/estabelecimento/equipe': typeof AuthenticatedEstabelecimentoEquipeRoute
  '/estabelecimento/estoque': typeof AuthenticatedEstabelecimentoEstoqueRoute
  '/estabelecimento/extrato': typeof AuthenticatedEstabelecimentoExtratoRoute
  '/estabelecimento/financeiro': typeof AuthenticatedEstabelecimentoFinanceiroRoute
  '/estabelecimento/horarios': typeof AuthenticatedEstabelecimentoHorariosRoute
  '/estabelecimento/pedidos': typeof AuthenticatedEstabelecimentoPedidosRoute
  '/estabelecimento/produtos': typeof AuthenticatedEstabelecimentoProdutosRoute
  '/estabelecimento/relatorios': typeof AuthenticatedEstabelecimentoRelatoriosRoute
  '/estabelecimento/saques': typeof AuthenticatedEstabelecimentoSaquesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/estabelecimento/': typeof AuthenticatedEstabelecimentoIndexRoute
  '/cliente/estabelecimento/$id': typeof AuthenticatedClienteEstabelecimentoIdRoute
  '/cliente/pedido/$id': typeof AuthenticatedClientePedidoIdRoute
  '/cliente/perfil/ajuda': typeof AuthenticatedClientePerfilAjudaRoute
  '/cliente/perfil/clube': typeof AuthenticatedClientePerfilClubeRoute
  '/cliente/perfil/conta': typeof AuthenticatedClientePerfilContaRoute
  '/cliente/perfil/dispositivo': typeof AuthenticatedClientePerfilDispositivoRoute
  '/cliente/perfil/enderecos': typeof AuthenticatedClientePerfilEnderecosRoute
  '/cliente/perfil/notificacoes': typeof AuthenticatedClientePerfilNotificacoesRoute
  '/cliente/perfil/recompensas': typeof AuthenticatedClientePerfilRecompensasRoute
  '/cliente/perfil/termos': typeof AuthenticatedClientePerfilTermosRoute
  '/entregador/perfil/dados': typeof AuthenticatedEntregadorPerfilDadosRoute
  '/entregador/perfil/pagamento': typeof AuthenticatedEntregadorPerfilPagamentoRoute
  '/cliente/perfil/': typeof AuthenticatedClientePerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-entrar': typeof AdminEntrarRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/estabelecimentos': typeof AuthenticatedAdminEstabelecimentosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/buscar': typeof AuthenticatedClienteBuscarRoute
  '/cliente/carrinho': typeof AuthenticatedClienteCarrinhoRoute
  '/cliente/checkout': typeof AuthenticatedClienteCheckoutRoute
  '/cliente/favoritos': typeof AuthenticatedClienteFavoritosRoute
  '/cliente/novidades': typeof AuthenticatedClienteNovidadesRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/entregador/avaliacoes': typeof AuthenticatedEntregadorAvaliacoesRoute
  '/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/entregador/chat': typeof AuthenticatedEntregadorChatRoute
  '/entregador/configuracoes': typeof AuthenticatedEntregadorConfiguracoesRoute
  '/entregador/corridas': typeof AuthenticatedEntregadorCorridasRoute
  '/entregador/documentos': typeof AuthenticatedEntregadorDocumentosRoute
  '/entregador/ganhos': typeof AuthenticatedEntregadorGanhosRoute
  '/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/entregador/metas': typeof AuthenticatedEntregadorMetasRoute
  '/entregador/notificacoes': typeof AuthenticatedEntregadorNotificacoesRoute
  '/entregador/perfil': typeof AuthenticatedEntregadorPerfilRouteWithChildren
  '/entregador/saques': typeof AuthenticatedEntregadorSaquesRoute
  '/entregador/suporte': typeof AuthenticatedEntregadorSuporteRoute
  '/entregador/veiculo': typeof AuthenticatedEntregadorVeiculoRoute
  '/estabelecimento/avaliacoes': typeof AuthenticatedEstabelecimentoAvaliacoesRoute
  '/estabelecimento/banners': typeof AuthenticatedEstabelecimentoBannersRoute
  '/estabelecimento/carteira': typeof AuthenticatedEstabelecimentoCarteiraRoute
  '/estabelecimento/categorias': typeof AuthenticatedEstabelecimentoCategoriasRoute
  '/estabelecimento/complementos': typeof AuthenticatedEstabelecimentoComplementosRoute
  '/estabelecimento/configuracoes': typeof AuthenticatedEstabelecimentoConfiguracoesRoute
  '/estabelecimento/cupons': typeof AuthenticatedEstabelecimentoCuponsRoute
  '/estabelecimento/entrega': typeof AuthenticatedEstabelecimentoEntregaRoute
  '/estabelecimento/equipe': typeof AuthenticatedEstabelecimentoEquipeRoute
  '/estabelecimento/estoque': typeof AuthenticatedEstabelecimentoEstoqueRoute
  '/estabelecimento/extrato': typeof AuthenticatedEstabelecimentoExtratoRoute
  '/estabelecimento/financeiro': typeof AuthenticatedEstabelecimentoFinanceiroRoute
  '/estabelecimento/horarios': typeof AuthenticatedEstabelecimentoHorariosRoute
  '/estabelecimento/pedidos': typeof AuthenticatedEstabelecimentoPedidosRoute
  '/estabelecimento/produtos': typeof AuthenticatedEstabelecimentoProdutosRoute
  '/estabelecimento/relatorios': typeof AuthenticatedEstabelecimentoRelatoriosRoute
  '/estabelecimento/saques': typeof AuthenticatedEstabelecimentoSaquesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/entregador': typeof AuthenticatedEntregadorIndexRoute
  '/estabelecimento': typeof AuthenticatedEstabelecimentoIndexRoute
  '/cliente/estabelecimento/$id': typeof AuthenticatedClienteEstabelecimentoIdRoute
  '/cliente/pedido/$id': typeof AuthenticatedClientePedidoIdRoute
  '/cliente/perfil/ajuda': typeof AuthenticatedClientePerfilAjudaRoute
  '/cliente/perfil/clube': typeof AuthenticatedClientePerfilClubeRoute
  '/cliente/perfil/conta': typeof AuthenticatedClientePerfilContaRoute
  '/cliente/perfil/dispositivo': typeof AuthenticatedClientePerfilDispositivoRoute
  '/cliente/perfil/enderecos': typeof AuthenticatedClientePerfilEnderecosRoute
  '/cliente/perfil/notificacoes': typeof AuthenticatedClientePerfilNotificacoesRoute
  '/cliente/perfil/recompensas': typeof AuthenticatedClientePerfilRecompensasRoute
  '/cliente/perfil/termos': typeof AuthenticatedClientePerfilTermosRoute
  '/entregador/perfil/dados': typeof AuthenticatedEntregadorPerfilDadosRoute
  '/entregador/perfil/pagamento': typeof AuthenticatedEntregadorPerfilPagamentoRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-entrar': typeof AdminEntrarRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRouteWithChildren
  '/_authenticated/estabelecimento': typeof AuthenticatedEstabelecimentoRouteWithChildren
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/_authenticated/admin/estabelecimentos': typeof AuthenticatedAdminEstabelecimentosRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/ia': typeof AuthenticatedAdminIaRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/cliente/buscar': typeof AuthenticatedClienteBuscarRoute
  '/_authenticated/cliente/carrinho': typeof AuthenticatedClienteCarrinhoRoute
  '/_authenticated/cliente/checkout': typeof AuthenticatedClienteCheckoutRoute
  '/_authenticated/cliente/favoritos': typeof AuthenticatedClienteFavoritosRoute
  '/_authenticated/cliente/novidades': typeof AuthenticatedClienteNovidadesRoute
  '/_authenticated/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/_authenticated/entregador/avaliacoes': typeof AuthenticatedEntregadorAvaliacoesRoute
  '/_authenticated/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/_authenticated/entregador/chat': typeof AuthenticatedEntregadorChatRoute
  '/_authenticated/entregador/configuracoes': typeof AuthenticatedEntregadorConfiguracoesRoute
  '/_authenticated/entregador/corridas': typeof AuthenticatedEntregadorCorridasRoute
  '/_authenticated/entregador/documentos': typeof AuthenticatedEntregadorDocumentosRoute
  '/_authenticated/entregador/ganhos': typeof AuthenticatedEntregadorGanhosRoute
  '/_authenticated/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/_authenticated/entregador/metas': typeof AuthenticatedEntregadorMetasRoute
  '/_authenticated/entregador/notificacoes': typeof AuthenticatedEntregadorNotificacoesRoute
  '/_authenticated/entregador/perfil': typeof AuthenticatedEntregadorPerfilRouteWithChildren
  '/_authenticated/entregador/saques': typeof AuthenticatedEntregadorSaquesRoute
  '/_authenticated/entregador/suporte': typeof AuthenticatedEntregadorSuporteRoute
  '/_authenticated/entregador/veiculo': typeof AuthenticatedEntregadorVeiculoRoute
  '/_authenticated/estabelecimento/avaliacoes': typeof AuthenticatedEstabelecimentoAvaliacoesRoute
  '/_authenticated/estabelecimento/banners': typeof AuthenticatedEstabelecimentoBannersRoute
  '/_authenticated/estabelecimento/carteira': typeof AuthenticatedEstabelecimentoCarteiraRoute
  '/_authenticated/estabelecimento/categorias': typeof AuthenticatedEstabelecimentoCategoriasRoute
  '/_authenticated/estabelecimento/complementos': typeof AuthenticatedEstabelecimentoComplementosRoute
  '/_authenticated/estabelecimento/configuracoes': typeof AuthenticatedEstabelecimentoConfiguracoesRoute
  '/_authenticated/estabelecimento/cupons': typeof AuthenticatedEstabelecimentoCuponsRoute
  '/_authenticated/estabelecimento/entrega': typeof AuthenticatedEstabelecimentoEntregaRoute
  '/_authenticated/estabelecimento/equipe': typeof AuthenticatedEstabelecimentoEquipeRoute
  '/_authenticated/estabelecimento/estoque': typeof AuthenticatedEstabelecimentoEstoqueRoute
  '/_authenticated/estabelecimento/extrato': typeof AuthenticatedEstabelecimentoExtratoRoute
  '/_authenticated/estabelecimento/financeiro': typeof AuthenticatedEstabelecimentoFinanceiroRoute
  '/_authenticated/estabelecimento/horarios': typeof AuthenticatedEstabelecimentoHorariosRoute
  '/_authenticated/estabelecimento/pedidos': typeof AuthenticatedEstabelecimentoPedidosRoute
  '/_authenticated/estabelecimento/produtos': typeof AuthenticatedEstabelecimentoProdutosRoute
  '/_authenticated/estabelecimento/relatorios': typeof AuthenticatedEstabelecimentoRelatoriosRoute
  '/_authenticated/estabelecimento/saques': typeof AuthenticatedEstabelecimentoSaquesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/_authenticated/estabelecimento/': typeof AuthenticatedEstabelecimentoIndexRoute
  '/_authenticated/cliente/estabelecimento/$id': typeof AuthenticatedClienteEstabelecimentoIdRoute
  '/_authenticated/cliente/pedido/$id': typeof AuthenticatedClientePedidoIdRoute
  '/_authenticated/cliente/perfil/ajuda': typeof AuthenticatedClientePerfilAjudaRoute
  '/_authenticated/cliente/perfil/clube': typeof AuthenticatedClientePerfilClubeRoute
  '/_authenticated/cliente/perfil/conta': typeof AuthenticatedClientePerfilContaRoute
  '/_authenticated/cliente/perfil/dispositivo': typeof AuthenticatedClientePerfilDispositivoRoute
  '/_authenticated/cliente/perfil/enderecos': typeof AuthenticatedClientePerfilEnderecosRoute
  '/_authenticated/cliente/perfil/notificacoes': typeof AuthenticatedClientePerfilNotificacoesRoute
  '/_authenticated/cliente/perfil/recompensas': typeof AuthenticatedClientePerfilRecompensasRoute
  '/_authenticated/cliente/perfil/termos': typeof AuthenticatedClientePerfilTermosRoute
  '/_authenticated/entregador/perfil/dados': typeof AuthenticatedEntregadorPerfilDadosRoute
  '/_authenticated/entregador/perfil/pagamento': typeof AuthenticatedEntregadorPerfilPagamentoRoute
  '/_authenticated/cliente/perfil/': typeof AuthenticatedClientePerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-entrar'
    | '/auth'
    | '/cadastro'
    | '/entrar'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/cliente'
    | '/entregador'
    | '/estabelecimento'
    | '/admin/anuncios'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/estabelecimentos'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/mapa'
    | '/admin/notificacoes'
    | '/admin/pedidos'
    | '/admin/saques'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/cliente/buscar'
    | '/cliente/carrinho'
    | '/cliente/checkout'
    | '/cliente/favoritos'
    | '/cliente/novidades'
    | '/cliente/pedidos'
    | '/entregador/avaliacoes'
    | '/entregador/carteira'
    | '/entregador/chat'
    | '/entregador/configuracoes'
    | '/entregador/corridas'
    | '/entregador/documentos'
    | '/entregador/ganhos'
    | '/entregador/historico'
    | '/entregador/metas'
    | '/entregador/notificacoes'
    | '/entregador/perfil'
    | '/entregador/saques'
    | '/entregador/suporte'
    | '/entregador/veiculo'
    | '/estabelecimento/avaliacoes'
    | '/estabelecimento/banners'
    | '/estabelecimento/carteira'
    | '/estabelecimento/categorias'
    | '/estabelecimento/complementos'
    | '/estabelecimento/configuracoes'
    | '/estabelecimento/cupons'
    | '/estabelecimento/entrega'
    | '/estabelecimento/equipe'
    | '/estabelecimento/estoque'
    | '/estabelecimento/extrato'
    | '/estabelecimento/financeiro'
    | '/estabelecimento/horarios'
    | '/estabelecimento/pedidos'
    | '/estabelecimento/produtos'
    | '/estabelecimento/relatorios'
    | '/estabelecimento/saques'
    | '/api/public/seed-demo'
    | '/admin/'
    | '/cliente/'
    | '/entregador/'
    | '/estabelecimento/'
    | '/cliente/estabelecimento/$id'
    | '/cliente/pedido/$id'
    | '/cliente/perfil/ajuda'
    | '/cliente/perfil/clube'
    | '/cliente/perfil/conta'
    | '/cliente/perfil/dispositivo'
    | '/cliente/perfil/enderecos'
    | '/cliente/perfil/notificacoes'
    | '/cliente/perfil/recompensas'
    | '/cliente/perfil/termos'
    | '/entregador/perfil/dados'
    | '/entregador/perfil/pagamento'
    | '/cliente/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-entrar'
    | '/auth'
    | '/cadastro'
    | '/entrar'
    | '/login'
    | '/sitemap.xml'
    | '/app'
    | '/admin/anuncios'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/estabelecimentos'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/mapa'
    | '/admin/notificacoes'
    | '/admin/pedidos'
    | '/admin/saques'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/cliente/buscar'
    | '/cliente/carrinho'
    | '/cliente/checkout'
    | '/cliente/favoritos'
    | '/cliente/novidades'
    | '/cliente/pedidos'
    | '/entregador/avaliacoes'
    | '/entregador/carteira'
    | '/entregador/chat'
    | '/entregador/configuracoes'
    | '/entregador/corridas'
    | '/entregador/documentos'
    | '/entregador/ganhos'
    | '/entregador/historico'
    | '/entregador/metas'
    | '/entregador/notificacoes'
    | '/entregador/perfil'
    | '/entregador/saques'
    | '/entregador/suporte'
    | '/entregador/veiculo'
    | '/estabelecimento/avaliacoes'
    | '/estabelecimento/banners'
    | '/estabelecimento/carteira'
    | '/estabelecimento/categorias'
    | '/estabelecimento/complementos'
    | '/estabelecimento/configuracoes'
    | '/estabelecimento/cupons'
    | '/estabelecimento/entrega'
    | '/estabelecimento/equipe'
    | '/estabelecimento/estoque'
    | '/estabelecimento/extrato'
    | '/estabelecimento/financeiro'
    | '/estabelecimento/horarios'
    | '/estabelecimento/pedidos'
    | '/estabelecimento/produtos'
    | '/estabelecimento/relatorios'
    | '/estabelecimento/saques'
    | '/api/public/seed-demo'
    | '/admin'
    | '/cliente'
    | '/entregador'
    | '/estabelecimento'
    | '/cliente/estabelecimento/$id'
    | '/cliente/pedido/$id'
    | '/cliente/perfil/ajuda'
    | '/cliente/perfil/clube'
    | '/cliente/perfil/conta'
    | '/cliente/perfil/dispositivo'
    | '/cliente/perfil/enderecos'
    | '/cliente/perfil/notificacoes'
    | '/cliente/perfil/recompensas'
    | '/cliente/perfil/termos'
    | '/entregador/perfil/dados'
    | '/entregador/perfil/pagamento'
    | '/cliente/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-entrar'
    | '/auth'
    | '/cadastro'
    | '/entrar'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/cliente'
    | '/_authenticated/entregador'
    | '/_authenticated/estabelecimento'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/avaliacoes'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/campanhas'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/entregadores'
    | '/_authenticated/admin/estabelecimentos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/ia'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/mapa'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/saques'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/buscar'
    | '/_authenticated/cliente/carrinho'
    | '/_authenticated/cliente/checkout'
    | '/_authenticated/cliente/favoritos'
    | '/_authenticated/cliente/novidades'
    | '/_authenticated/cliente/pedidos'
    | '/_authenticated/entregador/avaliacoes'
    | '/_authenticated/entregador/carteira'
    | '/_authenticated/entregador/chat'
    | '/_authenticated/entregador/configuracoes'
    | '/_authenticated/entregador/corridas'
    | '/_authenticated/entregador/documentos'
    | '/_authenticated/entregador/ganhos'
    | '/_authenticated/entregador/historico'
    | '/_authenticated/entregador/metas'
    | '/_authenticated/entregador/notificacoes'
    | '/_authenticated/entregador/perfil'
    | '/_authenticated/entregador/saques'
    | '/_authenticated/entregador/suporte'
    | '/_authenticated/entregador/veiculo'
    | '/_authenticated/estabelecimento/avaliacoes'
    | '/_authenticated/estabelecimento/banners'
    | '/_authenticated/estabelecimento/carteira'
    | '/_authenticated/estabelecimento/categorias'
    | '/_authenticated/estabelecimento/complementos'
    | '/_authenticated/estabelecimento/configuracoes'
    | '/_authenticated/estabelecimento/cupons'
    | '/_authenticated/estabelecimento/entrega'
    | '/_authenticated/estabelecimento/equipe'
    | '/_authenticated/estabelecimento/estoque'
    | '/_authenticated/estabelecimento/extrato'
    | '/_authenticated/estabelecimento/financeiro'
    | '/_authenticated/estabelecimento/horarios'
    | '/_authenticated/estabelecimento/pedidos'
    | '/_authenticated/estabelecimento/produtos'
    | '/_authenticated/estabelecimento/relatorios'
    | '/_authenticated/estabelecimento/saques'
    | '/api/public/seed-demo'
    | '/_authenticated/admin/'
    | '/_authenticated/cliente/'
    | '/_authenticated/entregador/'
    | '/_authenticated/estabelecimento/'
    | '/_authenticated/cliente/estabelecimento/$id'
    | '/_authenticated/cliente/pedido/$id'
    | '/_authenticated/cliente/perfil/ajuda'
    | '/_authenticated/cliente/perfil/clube'
    | '/_authenticated/cliente/perfil/conta'
    | '/_authenticated/cliente/perfil/dispositivo'
    | '/_authenticated/cliente/perfil/enderecos'
    | '/_authenticated/cliente/perfil/notificacoes'
    | '/_authenticated/cliente/perfil/recompensas'
    | '/_authenticated/cliente/perfil/termos'
    | '/_authenticated/entregador/perfil/dados'
    | '/_authenticated/entregador/perfil/pagamento'
    | '/_authenticated/cliente/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminEntrarRoute: typeof AdminEntrarRoute
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-entrar': {
      id: '/admin-entrar'
      path: '/admin-entrar'
      fullPath: '/admin-entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estabelecimento': {
      id: '/_authenticated/estabelecimento'
      path: '/estabelecimento'
      fullPath: '/estabelecimento'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estabelecimento/': {
      id: '/_authenticated/estabelecimento/'
      path: '/'
      fullPath: '/estabelecimento/'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoIndexRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/entregador/': {
      id: '/_authenticated/entregador/'
      path: '/'
      fullPath: '/entregador/'
      preLoaderRoute: typeof AuthenticatedEntregadorIndexRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estabelecimento/saques': {
      id: '/_authenticated/estabelecimento/saques'
      path: '/saques'
      fullPath: '/estabelecimento/saques'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoSaquesRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/relatorios': {
      id: '/_authenticated/estabelecimento/relatorios'
      path: '/relatorios'
      fullPath: '/estabelecimento/relatorios'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoRelatoriosRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/produtos': {
      id: '/_authenticated/estabelecimento/produtos'
      path: '/produtos'
      fullPath: '/estabelecimento/produtos'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoProdutosRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/pedidos': {
      id: '/_authenticated/estabelecimento/pedidos'
      path: '/pedidos'
      fullPath: '/estabelecimento/pedidos'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoPedidosRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/horarios': {
      id: '/_authenticated/estabelecimento/horarios'
      path: '/horarios'
      fullPath: '/estabelecimento/horarios'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoHorariosRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/financeiro': {
      id: '/_authenticated/estabelecimento/financeiro'
      path: '/financeiro'
      fullPath: '/estabelecimento/financeiro'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/extrato': {
      id: '/_authenticated/estabelecimento/extrato'
      path: '/extrato'
      fullPath: '/estabelecimento/extrato'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoExtratoRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/estoque': {
      id: '/_authenticated/estabelecimento/estoque'
      path: '/estoque'
      fullPath: '/estabelecimento/estoque'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoEstoqueRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/equipe': {
      id: '/_authenticated/estabelecimento/equipe'
      path: '/equipe'
      fullPath: '/estabelecimento/equipe'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoEquipeRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/entrega': {
      id: '/_authenticated/estabelecimento/entrega'
      path: '/entrega'
      fullPath: '/estabelecimento/entrega'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoEntregaRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/cupons': {
      id: '/_authenticated/estabelecimento/cupons'
      path: '/cupons'
      fullPath: '/estabelecimento/cupons'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoCuponsRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/configuracoes': {
      id: '/_authenticated/estabelecimento/configuracoes'
      path: '/configuracoes'
      fullPath: '/estabelecimento/configuracoes'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/complementos': {
      id: '/_authenticated/estabelecimento/complementos'
      path: '/complementos'
      fullPath: '/estabelecimento/complementos'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoComplementosRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/categorias': {
      id: '/_authenticated/estabelecimento/categorias'
      path: '/categorias'
      fullPath: '/estabelecimento/categorias'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoCategoriasRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/carteira': {
      id: '/_authenticated/estabelecimento/carteira'
      path: '/carteira'
      fullPath: '/estabelecimento/carteira'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoCarteiraRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/banners': {
      id: '/_authenticated/estabelecimento/banners'
      path: '/banners'
      fullPath: '/estabelecimento/banners'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoBannersRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/estabelecimento/avaliacoes': {
      id: '/_authenticated/estabelecimento/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/estabelecimento/avaliacoes'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedEstabelecimentoRoute
    }
    '/_authenticated/entregador/veiculo': {
      id: '/_authenticated/entregador/veiculo'
      path: '/veiculo'
      fullPath: '/entregador/veiculo'
      preLoaderRoute: typeof AuthenticatedEntregadorVeiculoRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/suporte': {
      id: '/_authenticated/entregador/suporte'
      path: '/suporte'
      fullPath: '/entregador/suporte'
      preLoaderRoute: typeof AuthenticatedEntregadorSuporteRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/saques': {
      id: '/_authenticated/entregador/saques'
      path: '/saques'
      fullPath: '/entregador/saques'
      preLoaderRoute: typeof AuthenticatedEntregadorSaquesRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/perfil': {
      id: '/_authenticated/entregador/perfil'
      path: '/perfil'
      fullPath: '/entregador/perfil'
      preLoaderRoute: typeof AuthenticatedEntregadorPerfilRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/notificacoes': {
      id: '/_authenticated/entregador/notificacoes'
      path: '/notificacoes'
      fullPath: '/entregador/notificacoes'
      preLoaderRoute: typeof AuthenticatedEntregadorNotificacoesRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/metas': {
      id: '/_authenticated/entregador/metas'
      path: '/metas'
      fullPath: '/entregador/metas'
      preLoaderRoute: typeof AuthenticatedEntregadorMetasRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/historico': {
      id: '/_authenticated/entregador/historico'
      path: '/historico'
      fullPath: '/entregador/historico'
      preLoaderRoute: typeof AuthenticatedEntregadorHistoricoRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/ganhos': {
      id: '/_authenticated/entregador/ganhos'
      path: '/ganhos'
      fullPath: '/entregador/ganhos'
      preLoaderRoute: typeof AuthenticatedEntregadorGanhosRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/documentos': {
      id: '/_authenticated/entregador/documentos'
      path: '/documentos'
      fullPath: '/entregador/documentos'
      preLoaderRoute: typeof AuthenticatedEntregadorDocumentosRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/corridas': {
      id: '/_authenticated/entregador/corridas'
      path: '/corridas'
      fullPath: '/entregador/corridas'
      preLoaderRoute: typeof AuthenticatedEntregadorCorridasRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/configuracoes': {
      id: '/_authenticated/entregador/configuracoes'
      path: '/configuracoes'
      fullPath: '/entregador/configuracoes'
      preLoaderRoute: typeof AuthenticatedEntregadorConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/chat': {
      id: '/_authenticated/entregador/chat'
      path: '/chat'
      fullPath: '/entregador/chat'
      preLoaderRoute: typeof AuthenticatedEntregadorChatRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/carteira': {
      id: '/_authenticated/entregador/carteira'
      path: '/carteira'
      fullPath: '/entregador/carteira'
      preLoaderRoute: typeof AuthenticatedEntregadorCarteiraRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/entregador/avaliacoes': {
      id: '/_authenticated/entregador/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/entregador/avaliacoes'
      preLoaderRoute: typeof AuthenticatedEntregadorAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/cliente/pedidos': {
      id: '/_authenticated/cliente/pedidos'
      path: '/pedidos'
      fullPath: '/cliente/pedidos'
      preLoaderRoute: typeof AuthenticatedClientePedidosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/novidades': {
      id: '/_authenticated/cliente/novidades'
      path: '/novidades'
      fullPath: '/cliente/novidades'
      preLoaderRoute: typeof AuthenticatedClienteNovidadesRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/favoritos': {
      id: '/_authenticated/cliente/favoritos'
      path: '/favoritos'
      fullPath: '/cliente/favoritos'
      preLoaderRoute: typeof AuthenticatedClienteFavoritosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/checkout': {
      id: '/_authenticated/cliente/checkout'
      path: '/checkout'
      fullPath: '/cliente/checkout'
      preLoaderRoute: typeof AuthenticatedClienteCheckoutRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/carrinho': {
      id: '/_authenticated/cliente/carrinho'
      path: '/carrinho'
      fullPath: '/cliente/carrinho'
      preLoaderRoute: typeof AuthenticatedClienteCarrinhoRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/buscar': {
      id: '/_authenticated/cliente/buscar'
      path: '/buscar'
      fullPath: '/cliente/buscar'
      preLoaderRoute: typeof AuthenticatedClienteBuscarRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saques': {
      id: '/_authenticated/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AuthenticatedAdminSaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mapa': {
      id: '/_authenticated/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AuthenticatedAdminMapaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ia': {
      id: '/_authenticated/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AuthenticatedAdminIaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estabelecimentos': {
      id: '/_authenticated/admin/estabelecimentos'
      path: '/estabelecimentos'
      fullPath: '/admin/estabelecimentos'
      preLoaderRoute: typeof AuthenticatedAdminEstabelecimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entregadores': {
      id: '/_authenticated/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AuthenticatedAdminEntregadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campanhas': {
      id: '/_authenticated/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avaliacoes': {
      id: '/_authenticated/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/cliente/perfil/': {
      id: '/_authenticated/cliente/perfil/'
      path: '/perfil'
      fullPath: '/cliente/perfil/'
      preLoaderRoute: typeof AuthenticatedClientePerfilIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/entregador/perfil/pagamento': {
      id: '/_authenticated/entregador/perfil/pagamento'
      path: '/pagamento'
      fullPath: '/entregador/perfil/pagamento'
      preLoaderRoute: typeof AuthenticatedEntregadorPerfilPagamentoRouteImport
      parentRoute: typeof AuthenticatedEntregadorPerfilRoute
    }
    '/_authenticated/entregador/perfil/dados': {
      id: '/_authenticated/entregador/perfil/dados'
      path: '/dados'
      fullPath: '/entregador/perfil/dados'
      preLoaderRoute: typeof AuthenticatedEntregadorPerfilDadosRouteImport
      parentRoute: typeof AuthenticatedEntregadorPerfilRoute
    }
    '/_authenticated/cliente/perfil/termos': {
      id: '/_authenticated/cliente/perfil/termos'
      path: '/perfil/termos'
      fullPath: '/cliente/perfil/termos'
      preLoaderRoute: typeof AuthenticatedClientePerfilTermosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/recompensas': {
      id: '/_authenticated/cliente/perfil/recompensas'
      path: '/perfil/recompensas'
      fullPath: '/cliente/perfil/recompensas'
      preLoaderRoute: typeof AuthenticatedClientePerfilRecompensasRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/notificacoes': {
      id: '/_authenticated/cliente/perfil/notificacoes'
      path: '/perfil/notificacoes'
      fullPath: '/cliente/perfil/notificacoes'
      preLoaderRoute: typeof AuthenticatedClientePerfilNotificacoesRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/enderecos': {
      id: '/_authenticated/cliente/perfil/enderecos'
      path: '/perfil/enderecos'
      fullPath: '/cliente/perfil/enderecos'
      preLoaderRoute: typeof AuthenticatedClientePerfilEnderecosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/dispositivo': {
      id: '/_authenticated/cliente/perfil/dispositivo'
      path: '/perfil/dispositivo'
      fullPath: '/cliente/perfil/dispositivo'
      preLoaderRoute: typeof AuthenticatedClientePerfilDispositivoRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/conta': {
      id: '/_authenticated/cliente/perfil/conta'
      path: '/perfil/conta'
      fullPath: '/cliente/perfil/conta'
      preLoaderRoute: typeof AuthenticatedClientePerfilContaRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/clube': {
      id: '/_authenticated/cliente/perfil/clube'
      path: '/perfil/clube'
      fullPath: '/cliente/perfil/clube'
      preLoaderRoute: typeof AuthenticatedClientePerfilClubeRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil/ajuda': {
      id: '/_authenticated/cliente/perfil/ajuda'
      path: '/perfil/ajuda'
      fullPath: '/cliente/perfil/ajuda'
      preLoaderRoute: typeof AuthenticatedClientePerfilAjudaRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/pedido/$id': {
      id: '/_authenticated/cliente/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/cliente/pedido/$id'
      preLoaderRoute: typeof AuthenticatedClientePedidoIdRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/estabelecimento/$id': {
      id: '/_authenticated/cliente/estabelecimento/$id'
      path: '/estabelecimento/$id'
      fullPath: '/cliente/estabelecimento/$id'
      preLoaderRoute: typeof AuthenticatedClienteEstabelecimentoIdRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminAvaliacoesRoute: typeof AuthenticatedAdminAvaliacoesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCampanhasRoute: typeof AuthenticatedAdminCampanhasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEntregadoresRoute: typeof AuthenticatedAdminEntregadoresRoute
  AuthenticatedAdminEstabelecimentosRoute: typeof AuthenticatedAdminEstabelecimentosRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminIaRoute: typeof AuthenticatedAdminIaRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMapaRoute: typeof AuthenticatedAdminMapaRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminSaquesRoute: typeof AuthenticatedAdminSaquesRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminAvaliacoesRoute: AuthenticatedAdminAvaliacoesRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCampanhasRoute: AuthenticatedAdminCampanhasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminEntregadoresRoute: AuthenticatedAdminEntregadoresRoute,
  AuthenticatedAdminEstabelecimentosRoute:
    AuthenticatedAdminEstabelecimentosRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminIaRoute: AuthenticatedAdminIaRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminMapaRoute: AuthenticatedAdminMapaRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminSaquesRoute: AuthenticatedAdminSaquesRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClienteRouteChildren {
  AuthenticatedClienteBuscarRoute: typeof AuthenticatedClienteBuscarRoute
  AuthenticatedClienteCarrinhoRoute: typeof AuthenticatedClienteCarrinhoRoute
  AuthenticatedClienteCheckoutRoute: typeof AuthenticatedClienteCheckoutRoute
  AuthenticatedClienteFavoritosRoute: typeof AuthenticatedClienteFavoritosRoute
  AuthenticatedClienteNovidadesRoute: typeof AuthenticatedClienteNovidadesRoute
  AuthenticatedClientePedidosRoute: typeof AuthenticatedClientePedidosRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
  AuthenticatedClienteEstabelecimentoIdRoute: typeof AuthenticatedClienteEstabelecimentoIdRoute
  AuthenticatedClientePedidoIdRoute: typeof AuthenticatedClientePedidoIdRoute
  AuthenticatedClientePerfilAjudaRoute: typeof AuthenticatedClientePerfilAjudaRoute
  AuthenticatedClientePerfilClubeRoute: typeof AuthenticatedClientePerfilClubeRoute
  AuthenticatedClientePerfilContaRoute: typeof AuthenticatedClientePerfilContaRoute
  AuthenticatedClientePerfilDispositivoRoute: typeof AuthenticatedClientePerfilDispositivoRoute
  AuthenticatedClientePerfilEnderecosRoute: typeof AuthenticatedClientePerfilEnderecosRoute
  AuthenticatedClientePerfilNotificacoesRoute: typeof AuthenticatedClientePerfilNotificacoesRoute
  AuthenticatedClientePerfilRecompensasRoute: typeof AuthenticatedClientePerfilRecompensasRoute
  AuthenticatedClientePerfilTermosRoute: typeof AuthenticatedClientePerfilTermosRoute
  AuthenticatedClientePerfilIndexRoute: typeof AuthenticatedClientePerfilIndexRoute
}

const AuthenticatedClienteRouteChildren: AuthenticatedClienteRouteChildren = {
  AuthenticatedClienteBuscarRoute: AuthenticatedClienteBuscarRoute,
  AuthenticatedClienteCarrinhoRoute: AuthenticatedClienteCarrinhoRoute,
  AuthenticatedClienteCheckoutRoute: AuthenticatedClienteCheckoutRoute,
  AuthenticatedClienteFavoritosRoute: AuthenticatedClienteFavoritosRoute,
  AuthenticatedClienteNovidadesRoute: AuthenticatedClienteNovidadesRoute,
  AuthenticatedClientePedidosRoute: AuthenticatedClientePedidosRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
  AuthenticatedClienteEstabelecimentoIdRoute:
    AuthenticatedClienteEstabelecimentoIdRoute,
  AuthenticatedClientePedidoIdRoute: AuthenticatedClientePedidoIdRoute,
  AuthenticatedClientePerfilAjudaRoute: AuthenticatedClientePerfilAjudaRoute,
  AuthenticatedClientePerfilClubeRoute: AuthenticatedClientePerfilClubeRoute,
  AuthenticatedClientePerfilContaRoute: AuthenticatedClientePerfilContaRoute,
  AuthenticatedClientePerfilDispositivoRoute:
    AuthenticatedClientePerfilDispositivoRoute,
  AuthenticatedClientePerfilEnderecosRoute:
    AuthenticatedClientePerfilEnderecosRoute,
  AuthenticatedClientePerfilNotificacoesRoute:
    AuthenticatedClientePerfilNotificacoesRoute,
  AuthenticatedClientePerfilRecompensasRoute:
    AuthenticatedClientePerfilRecompensasRoute,
  AuthenticatedClientePerfilTermosRoute: AuthenticatedClientePerfilTermosRoute,
  AuthenticatedClientePerfilIndexRoute: AuthenticatedClientePerfilIndexRoute,
}

const AuthenticatedClienteRouteWithChildren =
  AuthenticatedClienteRoute._addFileChildren(AuthenticatedClienteRouteChildren)

interface AuthenticatedEntregadorPerfilRouteChildren {
  AuthenticatedEntregadorPerfilDadosRoute: typeof AuthenticatedEntregadorPerfilDadosRoute
  AuthenticatedEntregadorPerfilPagamentoRoute: typeof AuthenticatedEntregadorPerfilPagamentoRoute
}

const AuthenticatedEntregadorPerfilRouteChildren: AuthenticatedEntregadorPerfilRouteChildren =
  {
    AuthenticatedEntregadorPerfilDadosRoute:
      AuthenticatedEntregadorPerfilDadosRoute,
    AuthenticatedEntregadorPerfilPagamentoRoute:
      AuthenticatedEntregadorPerfilPagamentoRoute,
  }

const AuthenticatedEntregadorPerfilRouteWithChildren =
  AuthenticatedEntregadorPerfilRoute._addFileChildren(
    AuthenticatedEntregadorPerfilRouteChildren,
  )

interface AuthenticatedEntregadorRouteChildren {
  AuthenticatedEntregadorAvaliacoesRoute: typeof AuthenticatedEntregadorAvaliacoesRoute
  AuthenticatedEntregadorCarteiraRoute: typeof AuthenticatedEntregadorCarteiraRoute
  AuthenticatedEntregadorChatRoute: typeof AuthenticatedEntregadorChatRoute
  AuthenticatedEntregadorConfiguracoesRoute: typeof AuthenticatedEntregadorConfiguracoesRoute
  AuthenticatedEntregadorCorridasRoute: typeof AuthenticatedEntregadorCorridasRoute
  AuthenticatedEntregadorDocumentosRoute: typeof AuthenticatedEntregadorDocumentosRoute
  AuthenticatedEntregadorGanhosRoute: typeof AuthenticatedEntregadorGanhosRoute
  AuthenticatedEntregadorHistoricoRoute: typeof AuthenticatedEntregadorHistoricoRoute
  AuthenticatedEntregadorMetasRoute: typeof AuthenticatedEntregadorMetasRoute
  AuthenticatedEntregadorNotificacoesRoute: typeof AuthenticatedEntregadorNotificacoesRoute
  AuthenticatedEntregadorPerfilRoute: typeof AuthenticatedEntregadorPerfilRouteWithChildren
  AuthenticatedEntregadorSaquesRoute: typeof AuthenticatedEntregadorSaquesRoute
  AuthenticatedEntregadorSuporteRoute: typeof AuthenticatedEntregadorSuporteRoute
  AuthenticatedEntregadorVeiculoRoute: typeof AuthenticatedEntregadorVeiculoRoute
  AuthenticatedEntregadorIndexRoute: typeof AuthenticatedEntregadorIndexRoute
}

const AuthenticatedEntregadorRouteChildren: AuthenticatedEntregadorRouteChildren =
  {
    AuthenticatedEntregadorAvaliacoesRoute:
      AuthenticatedEntregadorAvaliacoesRoute,
    AuthenticatedEntregadorCarteiraRoute: AuthenticatedEntregadorCarteiraRoute,
    AuthenticatedEntregadorChatRoute: AuthenticatedEntregadorChatRoute,
    AuthenticatedEntregadorConfiguracoesRoute:
      AuthenticatedEntregadorConfiguracoesRoute,
    AuthenticatedEntregadorCorridasRoute: AuthenticatedEntregadorCorridasRoute,
    AuthenticatedEntregadorDocumentosRoute:
      AuthenticatedEntregadorDocumentosRoute,
    AuthenticatedEntregadorGanhosRoute: AuthenticatedEntregadorGanhosRoute,
    AuthenticatedEntregadorHistoricoRoute:
      AuthenticatedEntregadorHistoricoRoute,
    AuthenticatedEntregadorMetasRoute: AuthenticatedEntregadorMetasRoute,
    AuthenticatedEntregadorNotificacoesRoute:
      AuthenticatedEntregadorNotificacoesRoute,
    AuthenticatedEntregadorPerfilRoute:
      AuthenticatedEntregadorPerfilRouteWithChildren,
    AuthenticatedEntregadorSaquesRoute: AuthenticatedEntregadorSaquesRoute,
    AuthenticatedEntregadorSuporteRoute: AuthenticatedEntregadorSuporteRoute,
    AuthenticatedEntregadorVeiculoRoute: AuthenticatedEntregadorVeiculoRoute,
    AuthenticatedEntregadorIndexRoute: AuthenticatedEntregadorIndexRoute,
  }

const AuthenticatedEntregadorRouteWithChildren =
  AuthenticatedEntregadorRoute._addFileChildren(
    AuthenticatedEntregadorRouteChildren,
  )

interface AuthenticatedEstabelecimentoRouteChildren {
  AuthenticatedEstabelecimentoAvaliacoesRoute: typeof AuthenticatedEstabelecimentoAvaliacoesRoute
  AuthenticatedEstabelecimentoBannersRoute: typeof AuthenticatedEstabelecimentoBannersRoute
  AuthenticatedEstabelecimentoCarteiraRoute: typeof AuthenticatedEstabelecimentoCarteiraRoute
  AuthenticatedEstabelecimentoCategoriasRoute: typeof AuthenticatedEstabelecimentoCategoriasRoute
  AuthenticatedEstabelecimentoComplementosRoute: typeof AuthenticatedEstabelecimentoComplementosRoute
  AuthenticatedEstabelecimentoConfiguracoesRoute: typeof AuthenticatedEstabelecimentoConfiguracoesRoute
  AuthenticatedEstabelecimentoCuponsRoute: typeof AuthenticatedEstabelecimentoCuponsRoute
  AuthenticatedEstabelecimentoEntregaRoute: typeof AuthenticatedEstabelecimentoEntregaRoute
  AuthenticatedEstabelecimentoEquipeRoute: typeof AuthenticatedEstabelecimentoEquipeRoute
  AuthenticatedEstabelecimentoEstoqueRoute: typeof AuthenticatedEstabelecimentoEstoqueRoute
  AuthenticatedEstabelecimentoExtratoRoute: typeof AuthenticatedEstabelecimentoExtratoRoute
  AuthenticatedEstabelecimentoFinanceiroRoute: typeof AuthenticatedEstabelecimentoFinanceiroRoute
  AuthenticatedEstabelecimentoHorariosRoute: typeof AuthenticatedEstabelecimentoHorariosRoute
  AuthenticatedEstabelecimentoPedidosRoute: typeof AuthenticatedEstabelecimentoPedidosRoute
  AuthenticatedEstabelecimentoProdutosRoute: typeof AuthenticatedEstabelecimentoProdutosRoute
  AuthenticatedEstabelecimentoRelatoriosRoute: typeof AuthenticatedEstabelecimentoRelatoriosRoute
  AuthenticatedEstabelecimentoSaquesRoute: typeof AuthenticatedEstabelecimentoSaquesRoute
  AuthenticatedEstabelecimentoIndexRoute: typeof AuthenticatedEstabelecimentoIndexRoute
}

const AuthenticatedEstabelecimentoRouteChildren: AuthenticatedEstabelecimentoRouteChildren =
  {
    AuthenticatedEstabelecimentoAvaliacoesRoute:
      AuthenticatedEstabelecimentoAvaliacoesRoute,
    AuthenticatedEstabelecimentoBannersRoute:
      AuthenticatedEstabelecimentoBannersRoute,
    AuthenticatedEstabelecimentoCarteiraRoute:
      AuthenticatedEstabelecimentoCarteiraRoute,
    AuthenticatedEstabelecimentoCategoriasRoute:
      AuthenticatedEstabelecimentoCategoriasRoute,
    AuthenticatedEstabelecimentoComplementosRoute:
      AuthenticatedEstabelecimentoComplementosRoute,
    AuthenticatedEstabelecimentoConfiguracoesRoute:
      AuthenticatedEstabelecimentoConfiguracoesRoute,
    AuthenticatedEstabelecimentoCuponsRoute:
      AuthenticatedEstabelecimentoCuponsRoute,
    AuthenticatedEstabelecimentoEntregaRoute:
      AuthenticatedEstabelecimentoEntregaRoute,
    AuthenticatedEstabelecimentoEquipeRoute:
      AuthenticatedEstabelecimentoEquipeRoute,
    AuthenticatedEstabelecimentoEstoqueRoute:
      AuthenticatedEstabelecimentoEstoqueRoute,
    AuthenticatedEstabelecimentoExtratoRoute:
      AuthenticatedEstabelecimentoExtratoRoute,
    AuthenticatedEstabelecimentoFinanceiroRoute:
      AuthenticatedEstabelecimentoFinanceiroRoute,
    AuthenticatedEstabelecimentoHorariosRoute:
      AuthenticatedEstabelecimentoHorariosRoute,
    AuthenticatedEstabelecimentoPedidosRoute:
      AuthenticatedEstabelecimentoPedidosRoute,
    AuthenticatedEstabelecimentoProdutosRoute:
      AuthenticatedEstabelecimentoProdutosRoute,
    AuthenticatedEstabelecimentoRelatoriosRoute:
      AuthenticatedEstabelecimentoRelatoriosRoute,
    AuthenticatedEstabelecimentoSaquesRoute:
      AuthenticatedEstabelecimentoSaquesRoute,
    AuthenticatedEstabelecimentoIndexRoute:
      AuthenticatedEstabelecimentoIndexRoute,
  }

const AuthenticatedEstabelecimentoRouteWithChildren =
  AuthenticatedEstabelecimentoRoute._addFileChildren(
    AuthenticatedEstabelecimentoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRouteWithChildren
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRouteWithChildren
  AuthenticatedEstabelecimentoRoute: typeof AuthenticatedEstabelecimentoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClienteRoute: AuthenticatedClienteRouteWithChildren,
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRouteWithChildren,
  AuthenticatedEstabelecimentoRoute:
    AuthenticatedEstabelecimentoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminEntrarRoute: AdminEntrarRoute,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
